'use strict';
// Gera System.json válido para RPG Maker MV.

function se(name, volume = 90, pitch = 100, pan = 0) { return { name, volume, pitch, pan }; }

function buildSystem({ switches, variables }) {
  return {
    airship: { bgm: se(''), characterIndex: 0, characterName: '', startMapId: 0, startX: 0, startY: 0 },
    armorTypes: ['', 'Couro', 'Cota de Malha', 'Placas', 'Manto Mágico', 'Escudo'],
    attackMotions: [
      { type: 0, weaponImageId: 0 }, { type: 1, weaponImageId: 1 }, { type: 1, weaponImageId: 2 },
      { type: 1, weaponImageId: 3 }, { type: 1, weaponImageId: 4 }, { type: 1, weaponImageId: 5 },
      { type: 2, weaponImageId: 6 }, { type: 2, weaponImageId: 7 }, { type: 0, weaponImageId: 8 },
      { type: 0, weaponImageId: 9 }, { type: 0, weaponImageId: 10 }, { type: 3, weaponImageId: 11 },
      { type: 2, weaponImageId: 12 },
    ],
    battleBgm: se('Battle1'),
    battleback1Name: '',
    battleback2Name: '',
    battlerHue: 0,
    battlerName: '',
    boat: { bgm: se('Ship1'), characterIndex: 0, characterName: 'Vehicle', startMapId: 0, startX: 0, startY: 0 },
    currencyUnit: 'Auros',
    defeatMe: se('Defeat1'),
    editMapId: 1,
    elements: ['', 'Físico', 'Luz', 'Sombra', 'Fogo', 'Gelo', 'Raio', 'Água', 'Terra', 'Vento', 'Aurora'],
    equipTypes: ['', 'Arma', 'Escudo', 'Elmo', 'Armadura', 'Acessório'],
    gameTitle: 'As Crônicas de Aethelgard',
    gameoverMe: se('Gameover1'),
    locale: 'pt_BR',
    magicSkills: [1],
    menuCommands: [true, true, true, true, true, true],
    optDisplayTp: true,
    optDrawTitle: true,
    optExtraExp: false,
    optFloorDeath: false,
    optFollowers: true,
    optSideView: false,
    optSlipDeath: false,
    optTransparent: false,
    partyMembers: [1, 2],
    ship: { bgm: se('Ship2'), characterIndex: 0, characterName: 'Vehicle', startMapId: 0, startX: 0, startY: 0 },
    sounds: [
      se('Cursor1'), se('Decision1'), se('Cancel1'), se('Buzzer1'), se('Equip1'),
      se('Save1'), se('Load1'), se('Battle1'), se('Escape3'), se('Sword2'),
      se('Damage4'), se('Collapse1'), se('Collapse2'), se('Collapse3'), se('Collapse4'),
      se('Recovery'), se('Miss'), se('Evasion1'), se('Evasion2'), se('Reflection'),
      se('Shop1'), se('Item3'), se('Item3'), se('Item1'),
    ],
    startMapId: 100, // mapa da cutscene de abertura (autorun)
    startX: 20,
    startY: 9,
    switches,
    terms: {
      basic: ['Nível', 'Nv', 'HP', 'HP', 'MP', 'MP', 'TP', 'TP', 'EXP', 'EXP'],
      commands: [
        'Lutar', 'Escapar', 'Atacar', 'Defender', 'Item', 'Habilidade', 'Equipar', 'Status',
        'Formação', 'Salvar', null, 'Sair', null, null, 'Armas', 'Armaduras', 'Itens-Chave',
        'Equipar', 'Otimizar', 'Limpar', 'Novo Jogo', 'Continuar', null, 'Para o Título',
        'Cancelar', null,
      ],
      params: ['HP Máx', 'MP Máx', 'Ataque', 'Defesa', 'At. Mágico', 'Def. Mágica', 'Agilidade', 'Sorte'],
      messages: {
        actionFailure: '%1 não sofreu dano!',
        actorDamage: '%1 sofreu %2 de dano!',
        actorDrain: '%2 de %1 foi drenado!',
        actorGain: '%1 ganhou %2 de %3!',
        actorLoss: '%1 perdeu %2 de %3!',
        actorNoDamage: '%1 não sofreu dano!',
        actorNoHit: 'Errou! %1 não sofreu dano!',
        actorRecovery: '%1 recuperou %2 de %3!',
        alwaysDash: 'Correr Sempre',
        bgmVolume: 'Volume BGM',
        bgsVolume: 'Volume BGS',
        buffAdd: '%2 de %1 aumentou!',
        buffRemove: '%2 de %1 voltou ao normal!',
        commandRemember: 'Lembrar Comando',
        counterAttack: '%1 contra-atacou!',
        criticalToActor: 'Golpe certeiro!!',
        criticalToEnemy: 'Golpe certeiro!!',
        debuffAdd: '%2 de %1 diminuiu!',
        defeat: '%1 foi derrotado.',
        emerge: '%1 apareceu!',
        escapeFailure: 'Falhou ao escapar!',
        escapeStart: '%1 fugiu!',
        evasion: '%1 esquivou do ataque!',
        expNext: 'EXP para o próximo %1',
        expTotal: 'EXP total atual',
        file: 'Arquivo',
        levelUp: '%1 subiu para %2 %3!',
        loadMessage: 'Carregar qual arquivo?',
        magicEvasion: '%1 anulou a magia!',
        magicReflection: '%1 refletiu a magia!',
        meVolume: 'Volume ME',
        obtainExp: '%1 EXP recebido!',
        obtainGold: '%1\\G recebido!',
        obtainItem: '%1 obtido!',
        obtainSkill: '%1 aprendido!',
        partyName: 'Grupo de %1',
        possession: 'Posse',
        preemptive: '%1 pegou o inimigo de surpresa!',
        rebirth: 'Reviveu!',
        saveMessage: 'Salvar em qual arquivo?',
        seVolume: 'Volume SE',
        substitute: '%1 protegeu %2!',
        surprise: '%1 foi pego de surpresa!',
        useItem: '%1 usa %2!',
        victory: '%1 venceu!',
      },
    },
    testBattlers: [
      { actorId: 1, equips: [1, 0, 3, 4, 0], level: 5 },
      { actorId: 2, equips: [2, 0, 3, 4, 0], level: 5 },
    ],
    testTroopId: 1,
    title1Name: '',
    title2Name: '',
    titleBgm: se('Theme1'),
    variables,
    versionId: Math.floor(Math.random() * 100000000),
    victoryMe: se('Victory1'),
    weaponTypes: ['', 'Espada', 'Cajado', 'Adaga', 'Machado', 'Arco', 'Lança', 'Punho'],
    windowTone: [0, 0, 0, 0],
  };
}

module.exports = { buildSystem };
